### ISSUE TITLE
Feature: Ability to Switch Live Camera Feeds

### ISSUE THREAD

**Issue by statueofmike** [subramgo/Akshi#3]

**Comment by statueofmike** [comment]
Here is my plan for adding object-detection live feed:

1. Start with TinyYOLO script developed here: https://github.com/statueofmike/akshi/blob/master/akshi/backend/monitor.py
2. Add a web service which serves the current static image
3. Akshi calls this webservice the same way it calls the current live network video sources

**Comment by statueofmike** [comment]
This code is in https://github.com/subramgo/Akshi/tree/master/akshi/object but needs to be integrated with the main Flask server, and see if the local URI can be plugged into the live view.

**Comment by subramgo** [comment]
COmpleted
