### ISSUE TITLE
Serve Annotated Images from Memory

### ISSUE THREAD

**Issue by statueofmike** [subramgo/Akshi#5]
Instead of writing an image file to disk to pass from a background process, we want our object-detection annotated images to go straight to the web GUI through working memory.

Maybe a useful lead here: https://fadeit.dk/blog/2015/04/30/python3-flask-pil-in-memory-image/

**Comment by subramgo** [comment]
Fixed

**Comment by subramgo** [comment]
The images are now read from memory from the camera and processed
